### ISSUE TITLE
Sending frames on already closed stream should raise RST_STREAM

### ISSUE THREAD

**Issue by squirrelfm** [molnarg/node-http2-protocol#10]
An endpoint MUST NOT send frames on a closed stream.  An endpoint that receives any frame after receiving a RST_STREAM MUST treat that as a stream error of type STREAM_CLOSED instead of sending GOAWAY frame (draft-09, section 5.1)

**Comment by molnarg** [comment]
Fixed by https://github.com/molnarg/node-http2-protocol/commit/4300e8903023c25a4049404fa07765f3ba8fb746 , thanks for reporting!
