### ISSUE TITLE
header compression error

### ISSUE THREAD

**Issue by tatsuhiro-t** [molnarg/node-http2-protocol#6]
Recently we have built some HPACK test cases https://github.com/Jxck/hpack-test-case
I'd like to add node-http2 compressor to there. While doing that, I found a bug in `HeaderTable.prototype._enforceLimit`. The code you should look at is:

```
droppedEntries[droppedEntries] = dropped;
```

`droppedEntries` is an array and stores the dropped entries. But the above code sets itself as index, which is apparently a bug.

I suspect that it is `dropPoint`, but I leave the fix for you. (I'm not really Nodejs guy)

The failed testcase is https://github.com/Jxck/hpack-test-case/blob/master/nghttp2/story_20.json When encoded by node-http2 compressor, at case #37 (1-based), it emits 2 empty name/value pairs.

**Comment by tatsuhiro-t** [comment]
One thing to note: In hpack-test-case, we currently don't incorporate cookie crumbling and NULL concatenated byte string in HPACK, because they are in HTTP layering. But it is merely a design decision whether to include them in compressor or not.

**Comment by molnarg** [comment]
Thanks for reporting, expect a fix at the weekend! You're probably right, but I'll look into it.

The HPACK test repo is a great idea. Do you already have the code needed for the integration or should I look into integrating it myself? I'll happily do that if you don't have the code yet.

**Comment by tatsuhiro-t** [comment]
Actually, I wrote one but accidentally lost it. Anyway, my nodejs knowledge is poor, you'd better write nice one.
Again, our HPACK implementations do not do cookie crumbling and 0x0 concatenation, so it would be good to add toggle switch to disable these features (or just comment out for this purpose only) when serializing output.

**Comment by molnarg** [comment]
Fixed, and I've submitted the pull request too: https://github.com/Jxck/hpack-test-case/pull/5
